- hosts: production
  become: yes
  vars_files:
    - ../group_vars/all.yml

  tasks:

    - name: Create Docker network for reverse proxy
      community.docker.docker_network:
        name: nginx-proxy
        driver: bridge

    - name: Free ports 80 and 443 if occupied
      shell: |
        for port in 80 443; do
          PID=$(lsof -ti :$port) && [ -n "$PID" ] && kill -9 $PID || true
        done
      ignore_errors: true

    - name: Start nginx-proxy container
      community.docker.docker_container:
        name: nginx-proxy
        image: jwilder/nginx-proxy
        restart_policy: always
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - /etc/nginx/certs:/etc/nginx/certs:ro
          - /etc/nginx/vhost.d:/etc/nginx/vhost.d
          - /usr/share/nginx/html:/usr/share/nginx/html
          - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
          - name: nginx-proxy

    - name: Start Let's Encrypt companion container
      community.docker.docker_container:
        name: nginx-letsencrypt
        image: jrcs/letsencrypt-nginx-proxy-companion
        restart_policy: always
        volumes:
          - /etc/nginx/certs:/etc/nginx/certs
          - /etc/nginx/vhost.d:/etc/nginx/vhost.d
          - /usr/share/nginx/html:/usr/share/nginx/html
          - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
          - name: nginx-proxy
        env:
          NGINX_PROXY_CONTAINER: nginx-proxy
          DEFAULT_EMAIL: "{{ email }}"

    - name: Start MySQL container
      community.docker.docker_container:
        name: mysql
        image: mysql:5.7
        restart_policy: always
        env:
          MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
          MYSQL_DATABASE: "{{ mysql_database }}"
          MYSQL_USER: "{{ mysql_user }}"
          MYSQL_PASSWORD: "{{ mysql_password }}"
        networks:
          - name: nginx-proxy

    - name: Start WordPress container
      community.docker.docker_container:
        name: wordpress
        image: wordpress:latest
        restart_policy: always
        env:
          WORDPRESS_DB_HOST: mysql:3306
          WORDPRESS_DB_USER: "{{ mysql_user }}"
          WORDPRESS_DB_PASSWORD: "{{ mysql_password }}"
          WORDPRESS_DB_NAME: "{{ mysql_database }}"
          VIRTUAL_HOST: "{{ domain }}"
          LETSENCRYPT_HOST: "{{ domain }}"
          LETSENCRYPT_EMAIL: "{{ email }}"
        expose:
          - 80
        networks:
          - name: nginx-proxy
