---
- hosts: production
  become: yes
  tasks:
    - name: Запуск контейнера MySQL
      community.docker.docker_container:
        name: mysql
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: "example"
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress
        ports:
          - "3306:3306"
        restart_policy: always

    - name: Запуск контейнера WordPress
      community.docker.docker_container:
        name: wordpress
        image: wordpress:latest
        env:
          WORDPRESS_DB_HOST: mysql:3306
          WORDPRESS_DB_USER: wordpress
          WORDPRESS_DB_PASSWORD: wordpress
          WORDPRESS_DB_NAME: wordpress
        ports:
          - "8080:80"
        links:
          - mysql
        restart_policy: always
