- name: Deploy WordPress and MySQL containers
  hosts: remote-server
  gather_facts: no
  become: yes
  tasks:
    - name: Pull MySQL image
      community.docker.docker_image:
        name: mysql:latest
        source: pull

    - name: Start MySQL container
      community.docker.docker_container:
        name: mysql
        image: mysql:latest
        state: started
        restart_policy: always
        env:
          MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
          MYSQL_DATABASE: "wordpress"
          MYSQL_USER: "wp_user"
          MYSQL_PASSWORD: "${MYSQL_USER_PASSWORD}"
        published_ports:
          - "3306:3306"

    - name: Pull WordPress image
      community.docker.docker_image:
        name: wordpress:latest
        source: pull

    - name: Start WordPress container
      community.docker.docker_container:
        name: wordpress
        image: wordpress:latest
        state: started
        restart_policy: always
        env:
          WORDPRESS_DB_HOST: "mysql:3306"
          WORDPRESS_DB_USER: "wp_user"
          WORDPRESS_DB_PASSWORD: "${MYSQL_USER_PASSWORD}"
          WORDPRESS_DB_NAME: "wordpress"
        published_ports:
          - "8080:80"
