# Общие настройки
server_ip: "your_server_ip"  # Переопределяется через --extra-vars
ssh_user: "deploy"

# Настройки MySQL
mysql_database: "wordpress"
mysql_user: "wpuser"

# Настройки WordPress
wp_port: 80

