---
- name: Deploy WordPress Stack
  hosts: all
  become: yes
  tasks:
    - name: Ensure directories exist
      file:
        path: /opt/wordpress
        state: directory
        mode: 0755

    - name: Deploy .env file
      template:
        src: ../../docker/templates/.env.j2
        dest: /opt/wordpress/.env
        mode: 0600

    - name: Deploy docker-compose.yml
      template:
        src: ../../docker/templates/docker-compose.j2
        dest: /opt/wordpress/docker-compose.yml
        mode: 0644

    - name: Install Docker Compose v2
      block:
        - name: Check if Docker Compose v2 is installed
          command: docker compose version
          register: compose_check
          ignore_errors: yes
          changed_when: false

        - name: Install Docker Compose plugin
          become: yes
          ansible.builtin.get_url:
            url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-{{ ansible_architecture }}"
            dest: /usr/libexec/docker/cli-plugins/docker-compose
            mode: '0755'
          when: compose_check.rc != 0

    - name: Start containers with Docker Compose v2
      community.docker.docker_compose_v2:
        project_src: /opt/wordpress
        state: present
        pull: true
        recreate: always
        env:
          MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
          MYSQL_PASSWORD: "{{ mysql_wp_password }}"

    - name: Verify services
      command: docker compose -f /opt/wordpress/docker-compose.yml ps
      register: services
      changed_when: false

    - name: Display services status
      debug:
        var: services.stdout_lines
