- name: Install Docker Compose plugin
  ansible.builtin.command: |
    docker compose version || (mkdir -p ~/.docker/cli-plugins && \
    curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 \
    -o ~/.docker/cli-plugins/docker-compose && \
    chmod +x ~/.docker/cli-plugins/docker-compose)
  changed_when: false

- name: Ensure deployment directory exists
  file:
    path: /opt/wordpress
    state: directory
    mode: 0755

- name: Deploy .env file
  template:
    src: .env.j2
    dest: /opt/wordpress/.env
    mode: 0600

- name: Deploy docker-compose.yml
  template:
    src: docker-compose.prod.yml.j2
    dest: /opt/wordpress/docker-compose.yml
    mode: 0644

- name: Pull Docker images
  community.docker.docker_compose_v2:
    project_src: /opt/wordpress
    pull: yes

- name: Start containers
  community.docker.docker_compose_v2:
    project_src: /opt/wordpress
    build: no
    state: present
    recreate: always
    remove_orphans: yes

- name: Verify services
  command: docker compose -f /opt/wordpress/docker-compose.yml ps
  register: services_status
  changed_when: false

- name: Show services status
  debug:
    var: services_status.stdout_lines