- name: Install Docker Compose plugin (official method)
  block:
    - name: Check if Docker Compose v2 is already installed
      command: docker compose version
      register: compose_check
      ignore_errors: yes
      changed_when: false

    - name: Download Docker Compose plugin
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-{{ ansible_architecture }}
        dest: /usr/libexec/docker/cli-plugins/docker-compose
        mode: '0755'
        owner: root
        group: root
      when: compose_check.rc != 0
      register: download_compose

    - name: Create symlink for Docker Compose
      file:
        src: /usr/libexec/docker/cli-plugins/docker-compose
        dest: /usr/bin/docker-compose
        state: link
      when: download_compose.changed
  become: yes

- name: Ensure deployment directory exists
  file:
    path: /opt/wordpress
    state: directory
    mode: 0755

- name: Deploy .env file
  template:
    src: .env.j2
    dest: /opt/wordpress/.env
    mode: 0600

- name: Deploy docker-compose.yml
  template:
    src: docker-compose.prod.yml.j2
    dest: /opt/wordpress/docker-compose.yml
    mode: 0644

- name: Pull Docker images
  community.docker.docker_compose_v2:
    project_src: /opt/wordpress
    pull: always

- name: Start containers
  community.docker.docker_compose_v2:
    project_src: /opt/wordpress
    build: no
    state: present
    recreate: always
    remove_orphans: yes

- name: Verify services
  command: docker compose -f /opt/wordpress/docker-compose.yml ps
  register: services_status
  changed_when: false

- name: Show services status
  debug:
    var: services_status.stdout_lines