- name: Ensure WordPress directory exists
  file:
    path: /opt/wordpress
    state: directory
    mode: 0755
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
- name: Create MySQL environment file
  copy:
    content: |
      MYSQL_ROOT_PASSWORD={{ mysql_root_password }}
      MYSQL_DATABASE=wordpress
      MYSQL_USER=wpuser
      MYSQL_PASSWORD={{ mysql_wp_password }}
    dest: /opt/wordpress/.mysql.env
    mode: 0600