name: 🚀 Deploy to Server

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout Repository
        uses: actions/checkout@v3

      - name: 🔐 Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 🔄 Force update known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keygen -R 51.250.9.118 -f ~/.ssh/known_hosts || true
          ssh-keyscan -H 51.250.9.118 >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts

      - name: 📦 Copy Project to Server
        run: |
          ssh verhanasta@51.250.9.118 "rm -rf ~/project"
          scp -r ./ verhanasta@51.250.9.118:~/project

      - name: 🧼 Clean Up Old Containers
        run: ssh verhanasta@51.250.9.118 "docker rm -f \$(docker ps -aq) || true"

      - name: 🧰 Install Ansible (if not installed)
        run: ssh verhanasta@51.250.9.118 "command -v ansible-playbook || (sudo apt update && sudo apt install -y ansible)"

      - name: 🕵️ Проверка SSH
        run: ssh -o StrictHostKeyChecking=no verhanasta@51.250.9.118 "echo '✅ SSH работает!'"

      - name: 🚀 Run Ansible Playbook
        run: ssh verhanasta@51.250.9.118 "cd ~/project && ansible-playbook -i ansible/inventory.ini ansible/deploy.yml"

      - name: 🧪 Проверка доступности сайта
        run: |
          echo "⏳ Ждём 30 секунд, чтобы сервисы успели подняться..."
          sleep 30
          echo "🌐 Проверяем https://51.250.9.118.sslip.io ..."
          STATUS=$(curl -L -s -k -o /dev/null -w '%{http_code}' https://51.250.9.118.sslip.io)
          echo "HTTP Status Code: $STATUS"
          if [ "$STATUS" != "200" ]; then
            echo "❌ Сайт недоступен или работает некорректно."
            exit 1
          fi
          echo "✅ Сайт доступен и работает корректно."
