name: Deploy WordPress

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Ansible and dependencies
        run: |
          pip install ansible docker
          ansible-galaxy collection install community.docker

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 51.250.9.118 >> ~/.ssh/known_hosts

      - name: Run playbook
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/deploy.yml

      - name: Wait for containers to start and verify site
        run: |
          echo "⏳ Ждём 30 секунд, чтобы сервисы успели подняться..."
          sleep 30
          
          echo "🌐 Проверяем доступность сайта https://51.250.9.118.sslip.io ..."
          STATUS=$(curl -L -k -s -o /dev/null -w '%{http_code}' https://51.250.9.118.sslip.io)
          echo "HTTP Status Code: $STATUS"
          
          if [ "$STATUS" != "200" ]; then
            echo "❌ Сайт недоступен или работает некорректно."
            exit 1
          fi
          
          echo "✅ Сайт доступен и работает корректно."