name: Production Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOMAIN: ${{ secrets.DOMAIN }}
      EMAIL: ${{ secrets.ADMIN_EMAIL }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible python3-pip
          pip3 install docker

      - name: Configure SSH Access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Run Ansible
        run: |
          cd ansible
          ansible-playbook -i inventory.yml \
            --extra-vars "mysql_root_password=$MYSQL_ROOT_PASSWORD \
                        mysql_wp_password=$MYSQL_WP_PASSWORD" \
            playbooks/site.yml -vv