name: Deploy WordPress

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Клонирование репозитория
        uses: actions/checkout@v4

      - name: 🔑 Установка SSH-ключа
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 51.250.9.118 >> ~/.ssh/known_hosts

      - name: 🛠️ Установка Ansible на сервере
        run: |
          ssh verhanasta@51.250.9.118 << 'EOF'
            sudo apt update
            sudo apt install -y ansible
          EOF

      - name: 🧹 Удаление всех контейнеров перед деплоем
        run: |
          ssh verhanasta@51.250.9.118 << 'EOF'
            echo "🧹 Удаляем все существующие контейнеры..."
            docker rm -f $(docker ps -aq) 2>/dev/null || true

            echo "🧼 Чистим неиспользуемые Docker-сети..."
            docker network prune -f
          EOF

      - name: 🚀 Запуск деплоя через Ansible
        run: |
          ssh verhanasta@51.250.9.118 "ansible-playbook -i ~/inventory.ini ~ansible/deploy.yml"

      - name: ⏳ Ожидание запуска сервисов
        run: sleep 30

      - name: 🌐 Проверка доступности сайта
        run: |
          STATUS=$(curl -L -k -s -o /dev/null -w '%{http_code}' https://51.250.9.118.sslip.io:8443)
          echo "HTTP Status Code: $STATUS"

          if [ "$STATUS" != "200" ]; then
            echo "❌ Сайт недоступен или работает некорректно."
            exit 1
          fi

          echo "✅ Сайт доступен и работает корректно."
